//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSoko.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int proid { get; set; }
        public string proname { get; set; }
        public string proimage { get; set; }
        public string prodescr { get; set; }
        public int proprice { get; set; }
        public Nullable<int> profkcatid { get; set; }
        public Nullable<int> profkuserid { get; set; }
        public string procontact { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
